version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: thuyen-silk-app-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=thuyen_silk
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - CRON_STANDALONE=false
    depends_on:
      - redis
      - postgres
    command: yarn dev
    networks:
      - thuyen-network

  cron:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: thuyen-silk-cron-dev
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - CRON_STANDALONE=true
    depends_on:
      - redis
    command: yarn dev:cron
    networks:
      - thuyen-network

  redis:
    image: redis:7-alpine
    container_name: thuyen-silk-redis-dev
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - thuyen-network

  postgres:
    image: postgres:14-alpine
    container_name: thuyen-silk-postgres-dev
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=thuyen_silk
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - thuyen-network

volumes:
  redis-data:
  postgres-data:

networks:
  thuyen-network:
    driver: bridge
